version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:secret@postgres:5432/postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
